# Generated by Django 4.2.7 on 2023-12-07 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LStore', '0002_alter_book_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='customer',
        ),
        migrations.AddField(
            model_name='customer',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LStore.book'),
        ),
    ]
