# Generated by Django 4.2.7 on 2023-12-07 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LStore', '0003_remove_book_customer_customer_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='book_category',
        ),
        migrations.AddField(
            model_name='book',
            name='book_category',
            field=models.ManyToManyField(related_name='categories', to='LStore.category'),
        ),
    ]
