# Generated by Django 4.2.7 on 2023-12-07 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LStore', '0004_remove_category_book_category_book_book_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
