# Generated by Django 4.2 on 2023-12-07 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LStore', '0005_alter_book_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='book',
        ),
    ]
