# Generated by Django 4.2 on 2023-12-15 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LStore', '0008_alter_book_description_alter_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(upload_to='uploads/'),
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='book',
        ),
        migrations.AddField(
            model_name='reservation',
            name='book',
            field=models.ManyToManyField(related_name='books', to='LStore.book'),
        ),
    ]
